### ISSUE TITLE
IC_GeneralFunctions.ahk missing?

### ISSUE THREAD

**Issue by geusr** [Leyline77/idleChampions-ahk#1]
Hi Leyline77

I wanted to give your scripts a try, but at least the file "IC_GeneralFunctions.ahk" seems to be missing.

When commenting out the corresponding #include, I get an error  in line 183 (LoadObjectFromJSON("idleChamp-leyline.JSON")).

Thanks and kind regards,
Roman

**Comment by Leyline77** [comment]
That means that your AHK is not loading from the target directory
containing the base script and all the files...
What I do is I make a shortcut that loads AHK and the script file name
and then in the working / target directory I put the path in like this:

Target:
D:\Dropbox\_tools\AutoHotkey.v1.1.33.10\AutoHotkeyU64.exe
idlechamp-v1.5-leyline.ahk
Start in:
D:\Dropbox\Games\IdleChampions\idleChampions-ahk.git\trunk\

[image: image.png]

**Comment by geusr** [comment]
Hi again

To me it looks more like the file "IC_GeneralFunctions.ahk" has not been pushed to github.

BTW: I can run the version of Oct 28, 2021, which does not yet require IC_GeneralFunctions.ahk.

Thanks,
Roman

**Comment by HFBPereira** [comment]
Hi, Layline77.

I have the same issue, looks like the IC_GeneralFunctions.ahk file isn't present in the code repository!

Thanks!

**Comment by Leyline77** [comment]
Oh I  really apologize that was some in development settings save / load jSON stuff.  I committed the file now.

**Comment by HFBPereira** [comment]
> Oh I really apologize that was some in development settings save / load jSON stuff. I committed the file now.

No need to apologize, this kind of thing happens.

Thanks for the script, improve a lot the gameplay!
